### ISSUE TITLE
大佬，hexo g报错，不知道咋回事

### ISSUE THREAD

**Issue by zhu-jiyuan** [Tomotoes/hexo-theme-tomotoes#19]
ERROR ReferenceError: E:\hexo\themes\tomotoes\layout\post.ejs:9
    7| %>
    8| <div class="container body-wrap">
 >> 9|     <%- partial('_partial/post', {post: page }) %>
    10| </div>
    11|

E:\hexo\themes\tomotoes\layout\_partial\post.ejs:24
    22|         </div>
    23|
 >> 24|         <%- partial('post/copyright') %>
    25|         <%- partial('post/reward-btn') %>
    26|
    27|         <div class="post-footer">

E:\hexo\themes\tomotoes\layout\_partial\post\copyright.ejs:5
    3|         <%- partial('updated') %>
    4|         <% if(theme.postMessage) {%>
 >> 5|         <%- _.template(theme.postMessage)(locals) %>
    6|         <% } %>
    7|     </div>
    8|     <footer>

_ is not defined
    at eval (E:\hexo\themes\tomotoes\layout\_partial\post\copyright.ejs:18:17)
    at copyright (E:\hexo\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (E:\hexo\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (E:\hexo\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (E:\hexo\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (E:\hexo\themes\tomotoes\layout\_partial\post.ejs:39:17)
    at post (E:\hexo\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (E:\hexo\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (E:\hexo\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (E:\hexo\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (E:\hexo\themes\tomotoes\layout\post.ejs:23:17)
    at post (E:\hexo\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\hexo\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\hexo\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\hexo\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at E:\hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\hexo\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  path: 'E:\\hexo\\themes\\tomotoes\\layout\\post.ejs'
}
ERROR ReferenceError: E:\hexo\themes\tomotoes\layout\archive.ejs:6
    4| }) %>
    5| <div class="container body-wrap fade">
 >> 6|     <%
    7|         var posts = [];
    8|
    9|         page.posts.each(function(post){

_ is not defined

**Comment by mutemad** [comment]
> ERROR ReferenceError: E:\hexo\themes\tomotoes\layout\post.ejs:9
> 7| %>
> 8|
> 
> > > 9|     <%- partial('_partial/post', {post: page }) %>
> > > 10|
> 
> 
> 11|
> E:\hexo\themes\tomotoes\layout_partial\post.ejs:24
> 22|
> 23|
> 
> > > 24|         <%- partial('post/copyright') %>
> > > 25|         <%- partial('post/reward-btn') %>
> > > 26|
> > > 27|
> 
> E:\hexo\themes\tomotoes\layout_partial\post\copyright.ejs:5
> 3| <%- partial('updated') %>
> 4| <% if(theme.postMessage) {%>
> 
> > > 5|         <%- _.template(theme.postMessage)(locals) %>
> > > 6|         <% } %>
> > > 7|     
> > > 8|
> 
> _ is not defined
> at eval (E:\hexo\themes\tomotoes\layout_partial\post\copyright.ejs:18:17)
> at copyright (E:\hexo\node_modules\ejs\lib\ejs.js:682:17)
> at _View._compiledSync (E:\hexo\node_modules\hexo\lib\theme\view.js:132:24)
> at _View.renderSync (E:\hexo\node_modules\hexo\lib\theme\view.js:59:25)
> at Object.partial (E:\hexo\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
> at eval (E:\hexo\themes\tomotoes\layout_partial\post.ejs:39:17)
> at post (E:\hexo\node_modules\ejs\lib\ejs.js:682:17)
> at _View._compiledSync (E:\hexo\node_modules\hexo\lib\theme\view.js:132:24)
> at _View.renderSync (E:\hexo\node_modules\hexo\lib\theme\view.js:59:25)
> at Object.partial (E:\hexo\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
> at eval (E:\hexo\themes\tomotoes\layout\post.ejs:23:17)
> at post (E:\hexo\node_modules\ejs\lib\ejs.js:682:17)
> at _View._compiled (E:\hexo\node_modules\hexo\lib\theme\view.js:136:50)
> at _View.render (E:\hexo\node_modules\hexo\lib\theme\view.js:39:17)
> at E:\hexo\node_modules\hexo\lib\hexo\index.js:64:21
> at tryCatcher (E:\hexo\node_modules\bluebird\js\release\util.js:16:23)
> at E:\hexo\node_modules\bluebird\js\release\method.js:15:34
> at RouteStream._read (E:\hexo\node_modules\hexo\lib\hexo\router.js:47:5) at RouteStream.Readable.read (internal/streams/readable.js:481:10) at resume_ (internal/streams/readable.js:968:12)
> at processTicksAndRejections (internal/process/task_queues.js:80:21) {
> path: 'E:\hexo\themes\tomotoes\layout\post.ejs'
> }
> ERROR ReferenceError: E:\hexo\themes\tomotoes\layout\archive.ejs:6
> 4| }) %>
> 5|
> 
> > > 6|     <%
> > > 7|         var posts = [];
> > > 8|
> > > 9|         page.posts.each(function(post){
> 
> _ is not defined
