### ISSUE TITLE
点击阅读原文报错

### ISSUE THREAD

**Issue by jrr997** [Tomotoes/hexo-theme-tomotoes#20]
**Describe the bug**
点击阅读原文之后页面一直在加载，且报错 _ is not defined。
其他issue中提到要安装完插件，我重新全部安装还是报错。
用的是最新的HEXO(5.0).

错误提示如下：
Unhandled rejection ReferenceError: C:\Users\Jrrr\Desktop\HEXO\themes\tomotoes\layout\post.ejs:9
    7| %>
    8|     <div class="container body-wrap">
 >> 9|       <%- partial('_partial/post', {post: page }) %>
    10|     </div>
    11| 

C:\Users\Jrrr\Desktop\HEXO\themes\tomotoes\layout\_partial\post.ejs:24
    22|         </div>
    23| 
 >> 24|         <%- partial('post/copyright') %>
    25|         <%- partial('post/reward-btn') %>
    26|
    27|         <div class="post-footer">

C:\Users\Jrrr\Desktop\HEXO\themes\tomotoes\layout\_partial\post\copyright.ejs:5
    3|     <%- partial('updated') %>
    4|       <% if(theme.postMessage) {%>
 >> 5|         <%- _.template(theme.postMessage)(locals) %>
    6|           <% } %>
    7|   </div>
    8|   <footer>

_ is not defined
    at eval (C:\Users\Jrrr\Desktop\HEXO\themes\tomotoes\layout\_partial\post\copyright.ejs:18:17)
    at copyright (C:\Users\Jrrr\Desktop\HEXO\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (C:\Users\Jrrr\Desktop\HEXO\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (C:\Users\Jrrr\Desktop\HEXO\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (C:\Users\Jrrr\Desktop\HEXO\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (C:\Users\Jrrr\Desktop\HEXO\themes\tomotoes\layout\_partial\post.ejs:39:17)
    at post (C:\Users\Jrrr\Desktop\HEXO\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (C:\Users\Jrrr\Desktop\HEXO\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (C:\Users\Jrrr\Desktop\HEXO\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (C:\Users\Jrrr\Desktop\HEXO\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (C:\Users\Jrrr\Desktop\HEXO\themes\tomotoes\layout\post.ejs:23:17)
    at post (C:\Users\Jrrr\Desktop\HEXO\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (C:\Users\Jrrr\Desktop\HEXO\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (C:\Users\Jrrr\Desktop\HEXO\node_modules\hexo\lib\theme\view.js:39:17)
    at C:\Users\Jrrr\Desktop\HEXO\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (C:\Users\Jrrr\Desktop\HEXO\node_modules\bluebird\js\release\util.js:16:23)
    at C:\Users\Jrrr\Desktop\HEXO\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (C:\Users\Jrrr\Desktop\HEXO\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:481:10)
    at resume_ (_stream_readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by jrr997** [comment]
其实ejs文件中很多处都有_.xx方法，不过我实在不明白这个_是什么意思，也找不到他的来源

**Comment by PpiERo** [comment]
是Lodash里的方法。hexo5.0以后Lodash已从全局变量中移除 可以参考[ You-Dont-Need-Lodash-Underscore](https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_sortby-and-_orderby)进行修改

**Comment by 502zl** [comment]
![QQ截图20210426014959](https://user-images.githubusercontent.com/48797792/116003734-c6920a00-a631-11eb-948d-4e5ef6f3a3fb.png)
你好，请问这个报错怎么解决啊？

**Comment by 502zl** [comment]
> ![QQ截图20210426014959](https://user-images.githubusercontent.com/48797792/116003734-c6920a00-a631-11eb-948d-4e5ef6f3a3fb.png)
> 你好，请问这个报错怎么解决啊？
降低hexo版本解决了

**Comment by struggle-bug** [comment]
请问以上问题解决了吗 ？我也有同样的问题

**Comment by 1ceC0la** [comment]
> > ![QQ截图20210426014959](https://user-images.githubusercontent.com/48797792/116003734-c6920a00-a631-11eb-948d-4e5ef6f3a3fb.png)
> > 你好，请问这个报错怎么解决啊？
> > 降低hexo版本解决了

请问怎么降低hexo版本

**Comment by Salmon-x** [comment]
同问，这个问题完全不会解决
![image](https://user-images.githubusercontent.com/63109044/131070341-c09f24c0-6227-406b-abf0-348a46b4d754.png)

**Comment by duramisu** [comment]
作者可以升级一下主题吗？支持最新的hexo，这个问题对于前端不熟悉的后端人员，完全无从下手

**Comment by SimonAKing** [comment]
抱歉，该主题已经多年不再维护了，请使用其他的主题吧。
