### ISSUE TITLE
hexo g的时候报错

### ISSUE THREAD

**Issue by hi-wendy** [Tomotoes/hexo-theme-tomotoes#3]
ERROR D:\git\hexo\blog.io\themes\tomotoes\layout\post.ejs:9
    7| %>
    8| <div class="container body-wrap">
 >> 9|     <%- partial('_partial/post', {post: page }) %>
    10| </div>
    11|

D:\git\hexo\blog.io\themes\tomotoes\layout\_partial\post.ejs:18
    16|         <div class="post-count-custom">
    17|             <i class="icon icon-lg icon-comment-o"></i>
 >> 18|             阅读本文可能花费您&nbsp;<span class="post-count"><%= min2read(post.content) %></span>&nbsp;分钟
    19|         </div>
    20|         <div class="post-content" id="post-content" itemprop="postContent">
    21|             <%- post.content %>

min2read is not defined
ReferenceError: D:\git\hexo\blog.io\themes\tomotoes\layout\post.ejs:9
    7| %>
    8| <div class="container body-wrap">
 >> 9|     <%- partial('_partial/post', {post: page }) %>
    10| </div>
    11|

D:\git\hexo\blog.io\themes\tomotoes\layout\_partial\post.ejs:18
    16|         <div class="post-count-custom">
    17|             <i class="icon icon-lg icon-comment-o"></i>
 >> 18|             阅读本文可能花费您&nbsp;<span class="post-count"><%= min2read(post.content) %></span>&nbsp;分钟
    19|         </div>
    20|         <div class="post-content" id="post-content" itemprop="postContent">
    21|             <%- post.content %>

min2read is not defined
    at eval (eval at compile (D:\git\hexo\blog.io\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:32:7)
    at returnedFn (D:\git\hexo\blog.io\node_modules\ejs\lib\ejs.js:580:17)
    at Theme._View.View._compiledSync (D:\git\hexo\blog.io\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (D:\git\hexo\blog.io\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (D:\git\hexo\blog.io\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (D:\git\hexo\blog.io\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at compile (D:\git\hexo\blog.io\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:22:17)
    at returnedFn (D:\git\hexo\blog.io\node_modules\ejs\lib\ejs.js:580:17)
    at Theme._View.View._compiled (D:\git\hexo\blog.io\node_modules\hexo\lib\theme\view.js:127:30)
    at Theme._View.View.View.render (D:\git\hexo\blog.io\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\git\hexo\blog.io\node_modules\hexo\lib\hexo\index.js:390:29
    at tryCatcher (D:\git\hexo\blog.io\node_modules\bluebird\js\release\util.js:16:23)
    at D:\git\hexo\blog.io\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\git\hexo\blog.io\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:443:10)
    at resume_ (_stream_readable.js:823:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
是怎么回事啊

**Comment by SimonAKing** [comment]
请直接阅读本项目文档，该装的插件都应该装上。
